disabled_rules:
- leading_whitespace
- trailing_whitespace
- nesting

excluded:
- Pods/
- YelloSakedong/Extension/
- YelloSakedong/Supporting Files/
- YelloSakedongTests/

line_length:
  warning: 99
  error: 120
